{
 "title": "Homework",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Disk Queue Length",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_diskio",
       "select": [
        [
         { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Current Disk Queue Length" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "% Disk Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Percent_Disk_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Disk Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "AVG. Disk Queue Length",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "AVG. Disk Queue Length" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "AVG. Disk sec/Read",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "AVG. Disk sec/Read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "AVG. Disk sec/Write",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "AVG. Disk sec/Write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Received/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes Received/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "Bytes Sent/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes Sent/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "Bytes Total/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Bytes_Total_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes Total/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available MBytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Available MBytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "% Committed Bytes In Use",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Committed Bytes In Use" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "Page Faults/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Page_Faults_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Page Faults/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "Pages/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Pages_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pages/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Processor Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Processor Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "% User Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Processor Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    },
    {
     "title": "Processor Queue Length",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$measurement, $col",
       "groupBy": [
        { "params": [ "3s" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_system",
       "select": [
        [
         { "params": [ "Processor_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Processor Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-D16P3PG" }
       ]
      }
     ]
    }
   ]
  }
 ]
}